### ISSUE TITLE
Setup editor option "Show all resources" should stay disabled or be preserved.

### ISSUE THREAD

**Issue by mmosconi1** [eclipse-oomph/oomph#100]
The option "Show all resources" automagically re-enables itself when I open some setup files or save changes.
Since this leads to loading of the whole universe of setups, it has a severe impact on the performance (esp. when live validation is enabled).

Could this be disabled by default and really only enabled temporarily on clicking the button?
Or at least the last setting of the user being preserved as default and not automatically switched back?

**Comment by merks** [comment]
They are always all loaded whether you see them or not.  I think they are only automatically all shown if any have errors which it think one would generally want to be aware.  Isn’t that the case?

**Comment by merks** [comment]
@mmosconi1 

I'm not sure you saw my question.   Generally all resources are not shown when you first open a editor, unless there are errors in the resource set, or when you drop a new resource onto the editor...

**Comment by merks** [comment]
I'll assume it's behaving as designed, i.e., showing extra resources only when there are errors in those resources.

**Comment by mmosconi1** [comment]
Sorry, I missed to answer. 
Currently we always have errors in some of our setups (big catalog maintained by several people), so that might be the reason.
