### ISSUE TITLE
problem with program files:i have practiced many programs on eclipse but after updating my laptop the the program files are deleted and its again asking download while opening eclipse

### ISSUE THREAD

**Issue by Kiruthigaarul** [eclipse-oomph/oomph#103]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.32.0+Build+468).

I understand that without details about the problem and how to reproduce the problem, no one can fix a problem for me.  Therefore I have clicked on the `Show Log` link on the red banner and have pasted the log details here:
```
Log Details...
```

**Comment by merks** [comment]
This doesn't sound like an installer problem.  There are really not enough details to even understand what problem you are having.
