### ISSUE TITLE
"Trust Artifacts" dialog not modal

### ISSUE THREAD

**Issue by jukzi** [eclipse-oomph/oomph#11]
it can hide behind the Eclipse Installer Window, which look and feels like program is stuck:
![image](https://github.com/eclipse-oomph/oomph/assets/51790620/ea7c1ea3-fee2-4928-9cc0-243dc31e7fc9)

**Comment by merks** [comment]
Yes, I've had that happen too, though in the Progress dialog in the IDE.  In any case, this would need to change in p2:

- https://github.com/eclipse-equinox/p2/blob/02f345d92a157d6bb14badae11f866daac01d11a/bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/TrustCertificateDialog.java#L85
- https://github.com/eclipse-equinox/p2/blob/02f345d92a157d6bb14badae11f866daac01d11a/bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/TrustAuthorityDialog.java#L86

**Comment by merks** [comment]
While I would like to make the dialog modal, doing so would affect not just the installer's use of it.  There is always a risk that a dialog such as this one that opens at some arbitrary time driven by a background job might appear while some other modal dialog/interaction is in progress.   Maybe I can do something that affects only the installer, e.g., looking for dialog shells when the installer shell is activated...

**Comment by merks** [comment]
I have a feeling that these dialogs could use SWT.ON_TOP rather than making them modal...

**Comment by merks** [comment]
After running into this twice this week, I decided to take action.  😱
