### ISSUE TITLE
Possible duplicate installations items

### ISSUE THREAD

**Issue by nlisker** [eclipse-oomph/oomph#110]
Using the installer's Advanced Mode and selecting Eclipse Platform to start from a minimal installation, the resulting Eclipse looks like:

![image](https://github.com/user-attachments/assets/1e070010-c680-4cb1-8e99-34f2d99875cc)

As can be seen, there are multiple items listed, but some already appear as subitems of others. `Eclipse RCP` and `feature.group Eclipse Platform` are both subitems in `ide Eclipse Platform` and individual items.

By trial and error, I uninstalled the "extra" items and got to

![image](https://github.com/user-attachments/assets/a9788317-9f92-4e05-9958-bababe29db7d)

This looks more correct to me. Is there a reason duplicate entries are added? Oomph can also be removed to reach the minimal platform, at least when bundles are not used.

**Comment by nlisker** [comment]
> Not really an Oomph question. The reason is that the roots of the tree are the things directly installed into the IDE, the so-called user roots. The content under them are things (features) includes included by those features, recursively.

But from the installer I only installed Eclipse Platform, not the other 2 items, why would they be installed separately?

**Comment by nlisker** [comment]
> I assume you installed this:

![image](https://github.com/user-attachments/assets/79c4e1eb-1e59-4fed-804c-6be21fca5e0e)

I installed the selected item - Eclipse Platform. The image you posted is also what I see if I go to the catalog.

> I think you're going to need to understand the models involved. You can use Navigate -> Open Setup -> Parent Models -> Catalog Index Eclipse to see all the models, unless of course you've uninstalled Oomph.

Yes, I do need to understand this.

> I get the sense you are fussing over things that don't really matter. In any case, if you want a define a product that is exactly and only exactly like you want it, you will have to define it yourself.

My goal is rather simple: create a minimal Eclipse on which I can install what I need.
Usually we are told that https://download.eclipse.org/eclipse/downloads/ contains the basic Eclipse package, without the prepared packages ("for Java developers", "for C/C++ developers", "for Web developers"...), but I found this to not really be the case just by going on adventures with the components. This link downloads the Eclipse SDK, which is also geared towards plugin developers and developers of the platform itself. If I look at its installation details, I see:

* ECF ... Developer Resources items
* Plugin Development Environment items
* EMF ... Developer Resources items
* Other development resources

I'd venture a guess that most Eclipse users don't need these because they don't write plugins or develop the platform. I could be wrong about this analysis. However, after installing the minimal Eclipse Platform + JDT I get what looks to me like a completely functional environment that is *less than twice the size and loads more than twice faster* than the one in the link above. Of course, then a run-of-the-mill developer might need to add some Mavan/Gradle plugins, Git integration and other common plugins like that.

> You can even go so far as to literally define a *.product file and use Tycho to build it (just like Oomph does for the Installer Product.)

This is what I was looking at, and I might do. It will basically be the Platform + JDT, which is a skinnier version of the SDK from the link.

**Comment by nlisker** [comment]
Is there a way to "Export" an installation? If I have an existing Eclipse with its components and I want to be able to duplicate it. Can I create a description file with the update sites and the plugins/features and use that?

**Comment by merks** [comment]
I'm not sure exactly what this operation does:

![image](https://github.com/user-attachments/assets/857fbf1e-459d-4d03-91a3-f72256686978)

**Comment by merks** [comment]
There's really no action to be take for this issue.

**Comment by nlisker** [comment]
> I'm not sure exactly what this operation does:
> 
> ![image](https://private-user-images.githubusercontent.com/208716/378096608-857fbf1e-459d-4d03-91a3-f72256686978.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTExNDQsIm5iZiI6MTcyOTM1MDg0NCwicGF0aCI6Ii8yMDg3MTYvMzc4MDk2NjA4LTg1N2ZiZjFlLTQ1OWQtNGQwMy05MWEzLWY3MjI1NjY4Njk3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNTE0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWFjNmUyNzBhYzU4NWEzNDIzOTUxZDIyZWUzZjU3Yzg3YzVmODk1ODNmYjdiMTE3ZTJhMzFhZWY1ZDExNjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FimQbHDvURA1EopxxcfrYq_HWMhp1SwZHyu4iuBIrr8)

Looks like this can work, thanks!
