### ISSUE TITLE
MyLynQueriesTask is breaking the installation of Eclipse versions using MyLyn >=4.0.0 P2 feature names (like e.g. Eclipse 2024-03)

### ISSUE THREAD

**Issue by mhoffrog** [eclipse-oomph/oomph#113]
**Issue:**
If my setups contain a `MyLynQueriesTask` and I am using an Eclipse version being configured for MyLyn 4.0.0+ P2 feature names, then the installer runs into unresovable P2 feature dependency conflicts.
In this case I did use **Eclipse 2024-03** for the setup.

**Root cause assumed**
The current [MyLyn.ecore](https://github.com/eclipse-oomph/oomph/blob/45a33a82ae2235a2486c19872fcb7e4fef632b73/setups/models/Mylyn.ecore#L22)  is defining feature `org.eclipse.mylyn.bugzilla_feature.feature.group`  for the `MyLynQueriesTask`. This feature name is not provided by MyLyn >=4.0.0 anymore as far as I can see. MyLyn did change the feature names with MyLyn 4.0.0 versus MyLyn 3.x.

**Workaround**
When I change the MyLyn features of the Eclipse product setup definitions using MyLyn 4+ feature names to optional, then the installation did work.

**Solution Proposal**
Remove or make the feature dependency `org.eclipse.mylyn.bugzilla_feature.feature.group` optional for `MyLynQueriesTask` installableUnits to be agnostic regarding the MyLyn version coming with Eclipse platform or being used by custom setups.

@merks
As far as I see the MyLyn features did "continuously" migrate from MyLyn 3.x to 4.x features within the following Eclipse product setups (checked for IDE for Java Developers only):
**2023-06**: MyLyn **3.x** features only
**2023-09**: MyLyn **4.x** features non optional, MyLyn **3.x** features **optional**
**2023-12**: MyLyn **4.x** features only, all MyLyn **3.x** named features **removed** - **except** `org.eclipse.mylyn.wikitext_feature.feature.group`
**2024-03**: MyLyn **4.x** features only, `org.eclipse.mylyn.wikitext.feature.feature.group` **added**, `org.eclipse.mylyn.wikitext_feature.feature.group` set to **optional**
**2024-06**: MyLyn **4.x** features only, `org.eclipse.mylyn.wikitext_feature.feature.group` **removed**
**2024-09**: same as 2024-06

**Comment by merks** [comment]
I see.  Sorry about that. I'm not bee using these tasks myself so didn't notice.

**Comment by merks** [comment]
I'm temped to just replace the feature requirement with these two bundle requirements because those have stable bundle symbolic names:

![image](https://github.com/user-attachments/assets/13cfe622-bd84-4303-901c-93e34af3212a)

The infrastructure doesn't current support specifying optional/greedy for these so this is the simplest solution.  Also, n a setup that uses these tasks, one can always require additional/other/broader features yourself so the most import thing to me seems to be avoiding trying to install something that doesn't exist...

@mhoffrog 

Does this seem okay?

**Comment by mhoffrog** [comment]
@merks Yes this is looking pretty good to me, since that would work for MyLyn 3.x as well as for MyLyn 4.x since both are providing those packages - correct?

**Comment by merks** [comment]
Oh dear, I see that even the update site we use is bad!

![image](https://github.com/user-attachments/assets/713e3302-8668-41a5-94bb-f5c01ffd5aa7)

We should be using this:

https://download.eclipse.org/mylyn/updates/release/latest

And yes, both this old release:

![image](https://github.com/user-attachments/assets/0cae6d56-1392-41aa-bf82-bba5cb09f250)

and the latest one have those bundles:

![image](https://github.com/user-attachments/assets/2d6ededb-45f1-421e-aaa3-33afe6eb4e86)

Only features were renamed...

Of course I will fix this as well!000

**Comment by merks** [comment]
Since I'm currently trying to build an m2a, I thought it best to include this fix while I'm at it.
