### ISSUE TITLE
Latest Oomph/Eclipse Installer on Linux issues on cert trust dialog

### ISSUE THREAD

**Issue by Mark-J-Lawrence** [eclipse-oomph/oomph#116]
For the very latest Eclipse Installer build (1.35.0 Build 900), when installing in a VM running RHEL 8.10, the trust certificates dialog can become tricky to progress from.

It works fine if I `Select All` and click `Trust Selected`, however, if I check `Always trust all content`, the `Always Trust Everything Confirmation` dialog doesn't appear, and its not possible to continue as normal (though I can press return as if the dialog is focused on somewhere, and the install continues and displays the same trust certs dialog again):

![image](https://github.com/user-attachments/assets/ac7e8d8b-f4c4-4dd4-b5cf-13d6478dc9fe)

I'm reporting this, though I've not tested on an actual RHEL 8.10 yet, but will soon.

**Comment by merks** [comment]
Note that these dialogs originate from p2 not directly from Oomph...
