### ISSUE TITLE
Problem with Installer Build 891 Version 1.35.0

### ISSUE THREAD

**Issue by itclientmanagement** [eclipse-oomph/oomph#117]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.35.0+Build+891).

I understand that without details about the problem and how to reproduce the problem, no one can fix a problem for me.  Therefore I have clicked on the `Show Log` link on the red banner and have pasted the log details here:
Log Details...
[logs.txt](https://github.com/user-attachments/files/17647582/logs.txt)

i'm using windows 11 enterprise 23h2 (company laptop) and also i'd like to ask if Zscaler could be related with that issue?

Kind Regards

**Comment by merks** [comment]
It seems you are just repeating yourself:

https://github.com/eclipse-packaging/packages/issues/230

But now it looks like you're failing to download artifacts without the PKIX:
```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
But it looks like lots of artifacts were downloaded before a bunch of them failed.

Yes, of not uncommon that virus scanners will cause problems by locking files such they after downloading they can't be moved to their final location.

If you try again,  the pool should slowly fill up such that you can run to completion.

**Comment by itclientmanagement** [comment]
Hi Merks!
First of all i'd like to appreacite your help on this topic! Yesterday we found the route of the cause and it was Zscaler whom was blocking the installation. Once we disabled we did not have any problem to install the installer paclkage.

**Comment by merks** [comment]
That’s good news!  Thanks for the feedback!
