### ISSUE TITLE
Extracting of linux archives with tar is failing

### ISSUE THREAD

**Issue by peterkir** [eclipse-oomph/oomph#119]
extraction of https://www.eclipse.org/downloads/download.php?file=/oomph/drops/release/1.34.0-a/products/**eclipse-inst-jre-linux64.tar.gz** archive is not working on linux.
tar is giving error messages like `tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'`

see also [Bug 582413](https://bugs.eclipse.org/bugs/show_bug.cgi?id=582413) - Valid Linux tar

**Comment by merks** [comment]
Those are warnings not errors aren't they?

In any case, they are created by Tycho but now Tycho supports disabling that...

**Comment by merks** [comment]
When this build finishes:

https://ci.eclipse.org/oomph/job/build/job/master/

The products here will be updated:

https://download.eclipse.org/oomph/products/latest/

And then you can confirm that they are fixed.

Of course all future builds will be configured to avoid this problem.

**Comment by merks** [comment]
FYI, in lots of places I've used the following: 
```
tar --warning=no-unknown-keyword -xf eclipse-inst-jre-linux64.tar.gz
```
So the installers are definitely not broken/invalid, just lots of annoying though suppressible warnings.
