### ISSUE TITLE
subclipse can't be installed

### ISSUE THREAD

**Issue by ccartee** [eclipse-oomph/oomph#12]
this link goes to a 404
https://subclipse.github.io/updates/subclipse/4.3.x

https://www.eclipse.org/setups/marketplace/?id=979

**Comment by merks** [comment]
It loads in the repository explorer:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/53039218-10f7-4fdc-88e5-41a60d759015)

Also, this file exists on the server:

https://subclipse.github.io/updates/subclipse/4.3.x/compositeContent.xml

So there is a repository there.  You just can't view the folder...
