### ISSUE TITLE
Problem with Installer Build 753 Version 1.34.0

### ISSUE THREAD

**Issue by mourya26** [eclipse-oomph/oomph#120]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.34.0+Build+753).

I understand that without details about the problem and how to reproduce the problem, no one can fix a problem for me.  Therefore I have clicked on the `Show Log` link on the red banner and have pasted the log details here:
```
Log Details...
```

**Comment by merks** [comment]
I can't help without details.  I'm going to assume you won't be providing details and will close it now.   If you can provide details, I'll be happy to take a lot.
