### ISSUE TITLE
Problem with Installer Build 5945 Version 1.29.0

### ISSUE THREAD

**Issue by Riyaz200** [eclipse-oomph/oomph#13]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.29.0+Build+5945).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...didnt install properly
```

**Comment by merks** [comment]
Given the lack of details, I cannot help fix anything.
