### ISSUE TITLE
Column header shrinkage in Bundle Pool Analysis dialog

### ISSUE THREAD

**Issue by dpetroff** [eclipse-oomph/oomph#14]
Whenever the columns are refreshed, like when the dialog is resized or when I hover over the column headers, the leftmost column shrinks.

This happens in Ubuntu with verssion 1.30.0 Build 5937.

https://github.com/eclipse-oomph/oomph/assets/1384881/c1e2a074-5dae-492f-b88b-da8a2b46d2fc

**Comment by merks** [comment]
That's strange.  It doesn't do that on Windows.  😢   There is auto resizing (column-packing) logic in there, so that must be misbehaving, but only on Linux...

**Comment by merks** [comment]
I think this is fixed.
