### ISSUE TITLE
Problem with Installer Build 5945 Version 1.29.0

### ISSUE THREAD

**Issue by Shubham-PW** [eclipse-oomph/oomph#15]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.29.0+Build+5945).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...
```

**Comment by merks** [comment]
I'm trying to guess what's wrong and coming up short on guesses.  Perhaps you can help with that?

**Comment by Shubham-PW** [comment]
Can you pls check my laptop.

**Comment by merks** [comment]
Of course I cannot check your laptop.   You need to provide details such as the log or screen captures.

**Comment by merks** [comment]
If you can provide details here, I can have a look.  But failing detail, I can do nothing.
