### ISSUE TITLE
Oomph since 1.29.0 forces https even for http repos

### ISSUE THREAD

**Issue by haubi** [eclipse-oomph/oomph#22]
So I've started to get familiar with the Oomph setup ecosystem, and figured to need some web server to provide one or another artifact.
For simplicity to find the way through, I'm using some local web server where I can either disable SSL, or have some self-signed certificate at hand only. The idea here is to learn what it needs before I ask our infra to provide a proper SSL enabled web server.

While making good progress with http repositories using Oomph up to version 1.28.0, Oomph version since 1.29.0 silently switches to https, and fails because of missing proper SSL setup in that local web server:

- Disabling SSL leads to 'Connection refused' at https port 443,
- Enabling SSL using self-signed certificate leads to 'unable to find valid certification path to requested target', because I don't use some public certification authority.

While I understand the motivation behind forcing https everywhere, either I need some option to disable that silent change to https, or I need some option to accept my self-signed certificate.

Thoughts?

**Comment by merks** [comment]
This is done by p2 for your safety and comfort:

https://eclipse.dev/eclipse/news/4.28/platform.php#force-https

You can change that via the preferences.
