### ISSUE TITLE
Debug option and system properties forwarding not working on JRE-bundled Win Installer

### ISSUE THREAD

**Issue by mmosconi1** [eclipse-oomph/oomph#31]
The following features are working with "eclipse-inst-win64.exe", but not with "eclipse-inst-jre-win64.exe":
- `--debug` flag (creation of extractor.log in target directory)
- forwarding of command line arguments to the target eclipse-inst.ini (https://bugs.eclipse.org/bugs/show_bug.cgi?id=546265)

**Comment by merks** [comment]
I don't think this is true.

When I run this:
```
merks@CORE MINGW64 /d/Users/merks
$/d/stuff/eclipse-inst-jre-win64\(28\).exe  --debug -consolelog -vmargs -Duser.home=D:/Users/test31
```
I see this printed from the debug logging:
```
Executing: "C:\Users\merks\AppData\Local\Temp\eoi29B2.tmp\eclipse-inst.exe" "-consolelog" "-vmargs" "-Duser.home=D:/Users/test31"
```
And, when the installer runs, I can see it's using that as the user.home and there is a terminal window launched for the console logging:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/209c8ff0-bea9-4704-9603-15b104046688)

Are you sure?

**Comment by mmosconi1** [comment]
Looks like the initial execution of the unpacked installer gets the command line args.
But they are not persisted in the eclipse-inst.ini, as they are with the non-JRE variant:
(left: eclipse-inst-win64.exe / right: eclipse-inst-jre-win64.exe)
![eclipse-inst-ini](https://github.com/eclipse-oomph/oomph/assets/117865836/f5e39137-2f71-4ff5-8200-696f70961248)
File extractor.log (from --debug flag) is also missing in the eoi*.tmp directory for the JRE variant.
Options used:
`--debug -vm C:\install\Java\jdk_17 -vmargs -Duser.home=C:\DEV_HOME\test\eclipse-installer-test\tmp-user-jre -Doomph.setup.user.home.redirect=true -Dfoo=bar`

This means that they are not available when switching to the advanced mode and they are not copied to the persistent location.

**Comment by mmosconi1** [comment]
Btw, adding `consoleLog` as in your example doesn't work together with a `-vm` option in both variants:
![consoleLog+vm](https://github.com/eclipse-oomph/oomph/assets/117865836/e78ab57f-b4c7-4f43-a96f-699cadf42bd6)
(seems that it doesn't look deeper into the specified `-vm` path to find the exectuable - it works without the `-consoleLog` option)

Btw 2, I was not able to debug in BINExtractor - it just doesn't suspend there. Any idea why?

**Comment by merks** [comment]
I forgot that it recorded those in the *.ini ever!  Switching between modes doesn't restart new JVM does it?

How are you trying to debug the BINExtractor?  That project has a very low BREE so that might be a problem...  I see it does this when I tried to just run it:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/2dbe9008-ec77-41f5-ba1d-7149cc6652cf)

These options need to be temporarily changed:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/1f3d8eff-234a-4230-a6d6-9ff75d5c6040)

**Comment by mmosconi1** [comment]
> Switching between modes doesn't restart new JVM does it?
Switching to advanced mode **without** copying to persistent location seems to not restart (arguments are still available), after copying, arguments are lost.
The missing entries in eclipse-inst.ini can be observed already in the eoi*.tmp directory in simple mode, without switching at all.
It appears to become a problem only when switching to the persistent location. Which is the main scenario, the Installer is used in our company: execute the .exe once and persist the installer (with additional .ini options, like redirections!) for workspace installations afterwards.

**Comment by mmosconi1** [comment]
Ok, it looks like BINExtractor.java is not invoked at all with the JRE-bundled .exe ... 😱 
That explains why all the adjustIni() logic and creation of extractor.log is not happening.

eclipse-inst-win64.exe:
```
Found marker
Found libdata.jar
Executing: "C:\install\Java\jdk_17\bin\javaw" -cp "C:\DEV_HOME\test\eclipse-installer-test\tmp-ecl\extD073.tmp.jar" org.eclipse.oomph.extractor.lib.JREValidator 11 0 0 64
Executing: "C:\install\Java\jdk_17\bin\javaw" -Dorg.eclipse.oomph.extractor.lib.BINExtractor.log=true -cp "C:\DEV_HOME\test\eclipse-installer-test\tmp-ecl\extD073.tmp.jar" org.eclipse.oomph.extractor.lib.BINExtractor "C:\DEV_HOME\eclipse\Eclipse-Projects\oomph-master2\git\oomph\products\org.eclipse.oomph.setup.installer.product\target\repackaged-products\eclipse-inst-win64.exe" "C:\DEV_HOME\test\eclipse-installer-test\tmp-ecl\eoiD0F1.tmp" "C:\install\Java\jdk_17" -- "-vmargs" "-Dfoo=bar"
```
eclipse-inst-jre-win64.exe:
```
Found marker
Found libdata.jar
Found start of product tar
Found end of product tar
Extracting from C:\DEV_HOME\test\eclipse-installer-test\tmp-ecl\proCB2C.tmp.tar to C:\DEV_HOME\test\eclipse-installer-test\tmp-ecl\eoiCC85.tmp\
  ...
End of C:\DEV_HOME\test\eclipse-installer-test\tmp-ecl\proCB2C.tmp.tar
Executing: "C:\DEV_HOME\test\eclipse-installer-test\tmp-ecl\eoiCC85.tmp\eclipse-inst.exe" "-vm" "C:\install\Java\jdk_17\bin" "-vmargs" "-Dfoo=bar"
```

So the problem lies in extractor.c, which I'm not able to debug or understand by reading the code...

**Comment by merks** [comment]
OMG, I really don't want to screw around n the native code.  That's a nightmare to change and I'm not a good C/C++ programmer.    

I'm starting to wonder if perhaps we could just make the logic in org.eclipse.oomph.setup.internal.installer.KeepInstallerUtil.keepInstaller(String, boolean, String, boolean, boolean, boolean) smarter so that it checks if the application was launched with a -vm and/or -vmargs sections and does the recording there? Then we can write it in Java code rather than in native code.  What do you think?

**Comment by merks** [comment]
It's hard to get that info though:

https://stackoverflow.com/questions/2541627/how-do-i-get-the-commandline-that-started-the-process

Maybe it will be good to understand the full use case for recording things in the permanent installer and what possible workaround might be acceptable...

**Comment by mmosconi1** [comment]
> I'm starting to wonder if perhaps we could just make the logic in ...

This basically does it:
![keepInstaller](https://github.com/eclipse-oomph/oomph/assets/117865836/dea773d8-a050-4d9d-a213-090c3d855cfa)
May need some polish or re-location of adjustIni() (to not depend on extractor.lib).

**Comment by merks** [comment]
The fix will be in the next nightly build and will be in this week's m2 milestone.
