### ISSUE TITLE
Problem with Installer Build 172 Version 1.30.0

### ISSUE THREAD

**Issue by Mohammad-Nuhiya** [eclipse-oomph/oomph#32]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.30.0+Build+172).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...
```

**Comment by merks** [comment]
There is no useful content in the issue.
