### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by mark-christiaens** [eclipse-oomph/oomph#36]
I'm trying to configure key bindings using Oomph but I'm failing. 

I start from a pristine, completely default set of key bindings and I'm trying to bind the `Format` command (currently bound to `Shift+Ctrl+F`) to `Shift+Ctrl+Alt+F12`.
![image](https://github.com/eclipse-oomph/oomph/assets/813926/1f45a1a1-01b8-45ce-a059-43f659cce8cc)
I press the Oomph recorder button and I perform the change.
![image](https://github.com/eclipse-oomph/oomph/assets/813926/8b811c00-5c9b-4294-bb07-641e0dc0b31e)
And then do `Apply and close`.  
The `org.eclipse.ui.commands` entry is updated in my setup file.
![image](https://github.com/eclipse-oomph/oomph/assets/813926/df8af28e-a46e-40e4-8eea-65c69a7f498d)
This is the XML of the change:
```
<?xml version="1.0" encoding="UTF-8"?>
<org.eclipse.ui.commands>
<keyBinding contextId="org.eclipse.ui.textEditorScope" keyConfigurationId="org.eclipse.ui.defaultAcceleratorConfiguration" keySequence="CTRL+SHIFT+F"/>
<keyBinding commandId="org.eclipse.lsp4e.format" contextId="org.eclipse.ui.textEditorScope" keyConfigurationId="org.eclipse.ui.defaultAcceleratorConfiguration" keySequence="ALT+CTRL+SHIFT+F12"/>
</org.eclipse.ui.commands>
```

I'm surprised that there is an entry:
```
<keyBinding contextId="org.eclipse.ui.textEditorScope" keyConfigurationId="org.eclipse.ui.defaultAcceleratorConfiguration" keySequence="CTRL+SHIFT+F"/>
```

IIUIC correctly, then this entry is responsible for unbinding the pre-existing key binding.  The surprising part is that it does not mention _which_ binding exactly to remove.  For example, it is possible that multiple bindings for this key-combination exists in the same scope.  

OK, nevermind, let's continue and try to use this recorded change. 

I revert the updated key bindings by pushing `Restore Defaults` in the `Keys` tab of the  `Preference` window.  

Now, I try to re-apply my recorded key bindings.  I do `Perform setup tasks`.
![image](https://github.com/eclipse-oomph/oomph/assets/813926/c69c5c16-b0f9-404f-a6de-54ac0bb59b5e)

The resulting key bindings are unexpected:
![image](https://github.com/eclipse-oomph/oomph/assets/813926/cfd01e81-767f-4cd9-8ecc-8743f133dfde)

There is no key binding for `Format`.  What is more, there is no key binding either for `Go to Symbol in File`, `Go to Symbol in Work` ...  They seem to have disappeared.  Note that not all key bindings have disappeared.  Most remain.

I'm using Eclipse 2023-03
![image](https://github.com/eclipse-oomph/oomph/assets/813926/fc0571a5-5a67-44f3-bb54-2dd2565f7a01)

**Comment by merks** [comment]
Yes, sorry, that doesn't work.  The representation is too complex/unusual to manage that way.  This is why there is specifically a Key Binding task

![image](https://github.com/eclipse-oomph/oomph/assets/208716/1ac4287d-b517-4f61-a384-9ba6c90bd916)

I've found them difficult to author though it does work...

**Comment by mark-christiaens** [comment]
I see.

I've added a `Key Binding Task` like so:

![image](https://github.com/eclipse-oomph/oomph/assets/813926/0e90285d-3a3e-4771-b9d3-3928719b774e)

which corresponds to this XML entry in my setup file:

```
<setupTask
        xsi:type="setup:CompoundTask"
        name="org.eclipse.ui.workbench">
      <setupTask
          xsi:type="workbench:KeyBindingTask"
          keys="ALT+CTRL+SHIFT+F10"
          command="org.eclipse.egit.ui.AbortRebase">
        <context
            id="org.eclipse.jdt.ui.javaEditorScope"/>
      </setupTask>
    </setupTask>
```

When I run my setup tasks, it doesn't seem to bind the key.  Am I missing something obvious?

**Comment by merks** [comment]
When I try to perform that task, the preferences show that it appears to be bound as expected:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/8e8ae5b0-1d30-4cf1-b0ad-b50f8e1895c0)

**Comment by mark-christiaens** [comment]
Got it to work.

For future reference, I learned stuff:

* One doesn't seem able to remove a key binding using a "key binding" task.  You can only add bindings.
* The underlying Eclipse key binding API seems flawed. `org.eclipse.jface.bindings.Binding` explains that you remove a key binding by registering a new binding that omits a command.  The problem is that this interface does not allow you to specifically say which binding needs to be removed: there could be multiple key bindings in the same scheme/context for the same key. It seems this interface will just randomly unbind one of possibly many bindings because the interface doesn't know which command is supposed to be unbound from the key.  That API also explains why the recorder sometimes registers multiple `keyBinding contextId="..." keyConfigurationId="..." keySequence="..."` operations.  I guess that the Preference dialog is just iterating through all the bindings of a key until it finally deletes the specific one you are trying to unbind.
