### ISSUE TITLE
Variables view should show Root installation folder in minimized mode

### ISSUE THREAD

**Issue by kthoms** [eclipse-oomph/oomph#39]
I'm setting up the Eclipse SDK with the [Auto Launch](https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup&show=true).

On the variables page I wondered to which directory the installation actually would happen and was missing this as an important information on the variables view. Of course I know that I can see this by use "Show all variables". However, I think it should be added to the minimized information.

![Bildschirm­foto 2023-11-01 um 09 04 08](https://github.com/eclipse-oomph/oomph/assets/265597/7cbbcb98-bdb3-4789-8561-8aa0b6f1c0d3)

**Comment by merks** [comment]
I really don't want to provide specialized support for special variables.  I expect a lot of information that might be considered important is hidden and of course the intent is that what you've decide before you don't need to be reminded of each time...

How about if instead the Confirmation page for bootstrap trigger (i.e., in the installer) shows that information like this?

![image](https://github.com/eclipse-oomph/oomph/assets/208716/c41060bc-6f34-4025-a83e-0552a36497dc)

**Comment by merks** [comment]
@kthoms @mmosconi1

I interpret a lack of response as full agreement.
