### ISSUE TITLE
TargetDefinitionGenerator does not put all the units in the target definition file

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-oomph/oomph#49]
Hi

I've just started experiment with the (cool) generator for the target platform definition file (https://wiki.eclipse.org/Eclipse_Oomph_Authoring#Generating_PDE_Target_Definition_files_.28.2A.target.29_and_their_use_by_Tycho).

I started to use that for EMF Parsley, the RAP version where defining a target definition file is a small nightmare (due to "slicer", required for RAP).

This is the content related in the setup file:

```xml
  <project name="rap"
      label="RAP">
    <setupTask
        xsi:type="setup.targlets:TargletTask">
      <targlet
          name="${scope.project.label}"
          activeRepositoryList="${eclipse.target.platform}"
          includeAllRequirements="false">
        <annotation
            source="http:/www.eclipse.org/oomph/targlets/TargetDefinitionGenerator">
          <detail
              key="location">
            <value>${git.clone.location}/devtools/org.eclipse.emf.parsley.targetplatform/simrel.rap.oomph.tp.target</value>
          </detail>
          <detail
              key="sortLocations">
            <value>false</value>
          </detail>
          <detail
              key="includeAllPlatforms">
            <value>false</value>
          </detail>
          <detail
              key="includeSource">
            <value>true</value>
          </detail>
          <detail
              key="singleLocation">
            <value>false</value>
          </detail>
          <detail
              key="extraUnits">
            <value>
              com.google.guava
              org.eclipse.emf.common
              org.eclipse.emf.edit
            </value>
          </detail>
        </annotation>
        <requirement
            name="org.eclipse.emf.parsley.rap.workspace.feature.group"/>
        <requirement
            name="org.eclipse.rap.feature.feature.group"/>
        <requirement
            name="org.eclipse.rap.sdk.feature.feature.group"/>
        <requirement
            name="org.eclipse.rap.examples.feature.feature.group"/>
        <requirement
            name="org.eclipse.rap.equinox.target.feature.feature.group"/>
        <requirement
            name="com.google.guava"/>
        <requirement
            name="org.eclipse.emf.common"/>
        <requirement
            name="org.eclipse.emf.ecore"/>
        <sourceLocator
            rootFolder="${git.clone.location}"
            locateNestedProjects="true"/>
...
```

And this is the generated target file:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="Generated from RAP" sequenceNumber="2">
  <locations>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
      <unit id="com.google.guava.failureaccess" version="0.0.0"/>
      <unit id="com.google.inject" version="0.0.0"/>
      <unit id="jakarta.inject.jakarta.inject-api" version="0.0.0"/>
      <unit id="org.aopalliance" version="0.0.0"/>
      <unit id="org.apache.log4j" version="0.0.0"/>
      <unit id="org.eclipse.xtext.xbase.lib" version="0.0.0"/>
      <unit id="org.junit" version="0.0.0"/>
      <unit id="org.objectweb.asm" version="0.0.0"/>
      <repository location="https://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.32.0"/>
    </location>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
      <unit id="org.apache.commons.logging" version="0.0.0"/>
      <unit id="org.eclipse.emf.cdo.net4j" version="0.0.0"/>
      <unit id="org.eclipse.emf.cdo.server.db" version="0.0.0"/>
      <unit id="org.eclipse.emf.cdo.server.net4j" version="0.0.0"/>
      <unit id="org.eclipse.emf.databinding.edit" version="0.0.0"/>
      <unit id="org.eclipse.emf.ecore.edit" version="0.0.0"/>
      <unit id="org.eclipse.emf.query" version="0.0.0"/>
      <unit id="org.eclipse.emf.rap" version="0.0.0"/>
      <unit id="org.eclipse.emf.rap.edit.ui" version="0.0.0"/>
      <unit id="org.eclipse.jetty.servlet-api" version="0.0.0"/>
      <unit id="org.eclipse.net4j.tcp" version="0.0.0"/>
      <unit id="org.eclipse.rap.equinox.target.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.rap.examples.feature.feature.group" version="0.0.0"/>
      <unit id="org.eclipse.rap.sdk.feature.feature.group" version="0.0.0"/>
      <unit id="org.objectweb.asm.commons" version="0.0.0"/>
      <unit id="org.objectweb.asm.tree" version="0.0.0"/>
      <unit id="org.objectweb.asm.tree.analysis" version="0.0.0"/>
      <unit id="org.objectweb.asm.util" version="0.0.0"/>
      <unit id="slf4j.simple" version="0.0.0"/>
      <repository location="https://download.eclipse.org/releases/2023-09"/>
    </location>
  </locations>
</target>
```

As you see, no matter what I added as requirements `com.google.guava`,  `org.eclipse.emf.common` and `org.eclipse.emf.edit` (I tried also as `extraUnits`) these units are not part of the generated target definition file...

am I doing anything wrong?

By the way, those 3 bundles are required for one of the projects imported in the workspace, so Oomph correctly puts them in the modular target platform, but not in the generated target file...

thanks in advance

**Comment by merks** [comment]
Lots of options have defaults that you likely don't not want that way.  It would be awfully helpful if there were no TODOs in the documentation and it described the defaults.  I've not tried generated targets involving slicer.  In any case, case I expect you really want `generateImplicitUnits=true`, `minimizeImplicitUnits =false`, and `generateVersions=true`.  That will produce the most details, including with exact versions.  Later you might see if you need that much locked-in detail.

**Comment by LorenzoBettini** [comment]
> Lots of options have defaults that you likely don't not want that way. It would be awfully helpful if there were no TODOs in the documentation and it described the defaults.

You mean in an ideal world! ;)

> I've not tried generated targets involving slicer. In any case, case I expect you really want `generateImplicitUnits=true`, `minimizeImplicitUnits =false`, and `generateVersions=true`. That will produce the most details, including with exact versions. Later you might see if you need that much locked-in detail.

Thank you @merks , these did the trick `generateImplicitUnits=true, minimizeImplicitUnits =false`

On a side note: I've just discovered that I can use a "planner" TP for RAP as well! In the past, I was including too many features in the TP (namely `org.eclipse.emf.cdo.feature.group` and `org.eclipse.net4j.feature.group`): these used to generate conflicts between RAP UI and RCP UI. But removing those features (not needed in the TP anyway), allows me to use "planner" and forget about the nightmares of "slider" :)

I guess we can close this issue.

**Comment by merks** [comment]
Yes, you should have asked a question.   😕

**Comment by LorenzoBettini** [comment]
> Yes, you should have asked a question. 😕

what do you mean?

**Comment by merks** [comment]
https://github.com/orgs/eclipse-oomph/discussions

**Comment by LorenzoBettini** [comment]
OK, I'm so sorry. I'm still not used to `discussions,` and this looked like a bug.

**Comment by merks** [comment]
It's not a problem at all!  And I don't really care one way or the other.  😄
