### ISSUE TITLE
[MacOS] Eclipse Installer: Launch automatically did no longer work for 2023-12 installations

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-oomph/oomph#52]
With Eclipse Installer 1.30.0 Build 172 you can not Install a 2023-12 version an get the new Instance up with the "Launch automatically".

If you did the same but install a 2023-09 the new Instance comes up automatically.

I found the following workaround.

```
  public Process execute(List<String> command, boolean terminal) throws Exception
  {
    ProcessBuilder processBuilder = new ProcessBuilder(command);
    try
    {
      Map<String, String> environment = processBuilder.environment();
      environment.remove("SWT_GTK3"); //$NON-NLS-1$
    }
    catch (UnsupportedOperationException ex)
    {
      // Ignore.
    }

    Process process = processBuilder.start();
    process.getInputStream().close();
    process.getOutputStream().close();
    process.getErrorStream().close();
    return process;
  }
```
If you insert `    TimeUnit.SECONDS.sleep(1);`
after `    Process process = processBuilder.start();`but before `process.getErrorStream().close();`
you can start a 2023-12 installation

**Comment by BeckerFrank** [comment]
Verifyed that this works with Nigthly Build Version  "1.31.0 Build 324"

**Comment by Mark-J-Lawrence** [comment]
I'm currently seeing this same issue again on "1.34.0 Build 753", no errors in any of the logs, so I may need to go down the path of debugging it, might be the exact same cause, might not.

**Comment by merks** [comment]
FYI. I tried for three days to install macOS on a virtualbox without success. Very frustrating and prevents me from helping here.  😞
