### ISSUE TITLE
Problem in installing the eclipse IDE

### ISSUE THREAD

**Issue by Yashuram-2003** [eclipse-oomph/oomph#53]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.29.0+Build+5945).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...
```

**Comment by merks** [comment]
I guessed that you experience a problem.  I just can’t guess what it might be. Can you share screenshots and logs to enlighten me?

**Comment by Yashuram-2003** [comment]
Yes, I can.
So look here it's showing like this from Last one hour...
It is not completing.....

**Comment by merks** [comment]
Your email replies show me nothing. Please use the browser to share details.

**Comment by merks** [comment]
I really would like to help, but I need details.  There is a new release and if the installer doesn't work for you, you can download a zip instead:

https://www.eclipse.org/downloads/packages/
