### ISSUE TITLE
Tycho pomless support?

### ISSUE THREAD

**Issue by kysmith-csg** [eclipse-oomph/oomph#55]
Oomph seems to not support importing tycho-pomless projects using the Maven Import task. During setup, the projects are able to be located in `MavenImportTask` (using `LocalProjectScanner` from m2e) but unable to be created because the `MavenProjectFactory` is only looking for files named `pom.xml` https://github.com/eclipse-oomph/oomph/blob/master/plugins/org.eclipse.oomph.resources/src/org/eclipse/oomph/resources/impl/MavenProjectFactoryImpl.java#L53. 

Do we have to use the `.project` files when importing tycho-pomless projects? It would be nice to not have to check these in.

**Comment by merks** [comment]
Does it work with m2e manually?  Is this something you could help improve/contribute assuming m2e can already do that?

**Comment by kysmith-csg** [comment]
m2e is able to import tycho-pomless projects fine. 

I did investigate how Oomph could support it but I think it would be a large change (although I'm not familiar at all with the codebase). It seems that the MavenProjectFactory (which extends XMLProjectFactory) only accepts a single file name, `pom.xml` in Maven's case. The issue is that Tycho generates many files that are equivalent to pom.xml, such as

pom.tycho
.polyglot.pom.tycho
.polyglot.META-INF
.polyglot.feature.xml

etc.

So either you have to create a factory for each of them, or modify the project factory system to allow a list of files to be given that are equivalent.

**Comment by merks** [comment]
Those other files are generated later in the build though aren't they, or do you check those in?

**Comment by kysmith-csg** [comment]
They are generated during the build yes, and **not** checked in. But m2e is able to import them despite the files not being there (I think they must do something to temporarily create them).

![image](https://github.com/eclipse-oomph/oomph/assets/136501322/6044d857-1ab3-4b3e-bde5-721ed81d319a)

I've debugged this and during the Maven import task we do get these projects (because m2e knows about it), but then the MavenProjectFactory only knows to look for pom.xml so the other ones are filtered.

`org.eclipse.oomph.resources.impl.XMLProjectFactoryImpl.doCreateProject(BackendContainer, BackendContainer, IProgressMonitor)`

```java
  @Override
  public final IProject doCreateProject(BackendContainer rootContainer, BackendContainer backendContainer, IProgressMonitor monitor)
  {
    IPath xmlFilePath = new Path(getXMLFileName());
    BackendFile xmlFile = null;

    try
    {
      xmlFile = backendContainer.getFile(xmlFilePath);

      byte[] bytes = xmlFile.getContentBytes(monitor);
      if (bytes.length > 0)
      {
        ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
        DocumentBuilder documentBuilder = XMLUtil.createDocumentBuilder();
        Element rootElement = XMLUtil.loadRootElement(documentBuilder, bais);

        Description description = new Description(backendContainer);
        fillDescription(description, rootElement);

        return new ExternalProject(backendContainer, description);
      }
    }
    catch (FileNotFoundException ex)
    {
      //$FALL-THROUGH$
    }
    catch (Exception ex)
    {
      String message = NLS.bind(Messages.XMLProjectFactoryImpl_ProblemParsing_exception, xmlFile != null ? xmlFile : xmlFilePath);
      ResourcesPlugin.INSTANCE.log(new Exception(message, ex));
    }

    return null;
  }
```

The XMLProjectFactory tries to find a file in the project for import. For Maven projects, `getXMLFileName()` returns `pom.xml`, and so `null` is returned since that file doesn't exist.

So my potential solutions would be:
1. Modify `XMLProjectFactory` to allow multiple filenames to search if one isn't found. Something like
```java
IPath xmlFilePath = null;
for (var filename : getXMLFileNames()) {
    xmlFilePath = new Path(filename);
    if (xmlFilePath.toFile().exists()) {
        break;
    }
}
...
```
2. Create a project factory for Tycho that knows about these files, similar to above but without modifying the original XMLProjectFactory. You could maybe get m2e to help the factory figure out what the appropriate file is (because there can be many e.g., `.polyglot.META-INF`, `.polyglot.feature.xml`, etc).


My first solution is probably better because they still are xml files, so we can benefit from the xml resource loading that the factory already does. We just have to teach it about different file names besides `pom.xml`.

**Comment by merks** [comment]
I suspect that something in m2e is just creating projects based on the folder names or some such thing.  We could look for things like a MANIFEST.MF, a feature.xml, or a category.xml.  At least the first two have IDs, but a category.xml does not.  That's what makes me think it's maybe just using the folder name as a project name.   But I don't have a good sense of what it all imports and how it decides what to import and how to assign Eclipse project names to those things.

I need to investigate further, but I have so little time and so much else to do.  😱
