### ISSUE TITLE
unable to open Problem with Installer Build 329 Version 1.31.0

### ISSUE THREAD

**Issue by tejalwaghmode** [eclipse-oomph/oomph#57]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.31.0+Build+329).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...
```

**Comment by merks** [comment]
Without details I can't help.
