### ISSUE TITLE
Provider Eclipse Installer for Windows ARM64/Aarch64

### ISSUE THREAD

**Issue by kwin** [eclipse-oomph/oomph#63]
Currently the Eclipse Installer is just provided for Windows as X86_64 binary in https://www.eclipse.org/downloads/packages/. This affects also all prebuilt packages.
Please provide the Installer as native [ARM binary for Windows](https://developer.arm.com/solutions/os/windows-on-arm) as well. This will probably require a [JustJ release](https://eclipse.dev/justj/) for Windows ARM as well. Unfortunately neither https://jdk.java.net/21/ nor https://adoptium.net/temurin/releases/?os=windows (https://github.com/adoptium/adoptium-support/issues/616) provide distributions for that architecture on Windows (yet).

**Comment by kwin** [comment]
> There is actually little point in having an open issue for this

I disagree with that. An open issue allows to track the progress and get notified via subscription once that is done. Also it allows to track potential upstream dependencies. It doesn't really matter how long it takes, it is just a matter of transparency.

**Comment by merks** [comment]
It’s not necessary for you to agree with me. 

In the interest of transparency, are you planning to do something somewhere or just asking and monitoring?

**Comment by kwin** [comment]
I don't plan to work on this in the near future, as soon as I start I will for sure add a comment here.

**Comment by chirontt** [comment]
@merks where is the installer code? I'll have a look to see if it can be compiled for Windows on Arm64.

Also, for the JustJ, I created some JustJ JREs in my [fork](https://github.com/chirontt/justj/releases), although I haven't done them recently. They were generated from the Microsoft JDKs for Windows on Arm64, but I don't know whether the resulting JREs can be used for Oomph (e.g. license, etc.) Do these JustJ JREs need be packaged in a p2 repo to be usable in a build?

**Comment by merks** [comment]
Yes, they need to be in a p2 repository.   

https://download.eclipse.org/justj/jres/17/updates/

We  also do not have approval for JustJ grabbing the originating JDK from some arbitrary source.  So it's essential that Adoptium provide the JDKs on a regular basis in lock-step with the other JREs so we can add the URL to this structure:

https://github.com/eclipse-justj/justj/blob/80c7b947140922a9d6bd1ef034d6601e2540ba06/releng/org.eclipse.justj.releng/Jenkinsfile#L41-L66

I understand that the Adoptium effort is started...

**Comment by chirontt** [comment]
> I understand that the Adoptium effort is started...

Great to hear this! At least things are moving forward, rather than standing still...
