### ISSUE TITLE
Problem with Installer Build 329 Version 1.31.0

### ISSUE THREAD

**Issue by Apoorva8112** [eclipse-oomph/oomph#71]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.31.0+Build+329).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...
![Screenshot 2024-03-06 002534](https://github.com/eclipse-oomph/oomph/assets/99011510/a6703c93-6906-48f2-b48c-5afa3d2973b0)


It prompts Failed Installation..What should I do?
```

**Comment by merks** [comment]
Click the Show log link and share those details. I can’t guess what has gone wrong just from the picture of the red banner with the link.

**Comment by merks** [comment]
I can't help without details about the problem.
