### ISSUE TITLE
Problem with Codeium plugin in Eclipse 2024-03

### ISSUE THREAD

**Issue by nelson777** [eclipse-oomph/oomph#75]
I installed Codeium plugin in the 2024-03 version of Eclipse and found that the suggestion disapears imediately after it apears. You can barely see it.

I'm using PHP version of Eclipse to develop in Angular/Typescript/Javascript.

I have installed the following plugins besides Codeium: Bash editor, Docker tooling, SQL Editor and Vrapper.

It works fine in 2023-12.

**Comment by nelson777** [comment]
Sorry for this... wrong repo

**Comment by nelson777** [comment]
Actually I'm reopening this as this project is linked in "Report problem" at the Codeium plugin's page:

https://www.eclipse.org/setups/marketplace/?id=5630287

If this is an error in the page please direct me to the correct place where I can open this issue. Thanks.

**Comment by merks** [comment]
Sorry, that's for reporting a problem about the report itself.

The listing itself

https://marketplace.eclipse.org/content/codeium

as a home link to this:

https://codeium.com/

and a help link to this:

https://discord.com/invite/3XFf78nAx5

The latter is probably the best place to start.
