### ISSUE TITLE
Problem with Installer Build 468 Version 1.32.0

### ISSUE THREAD

**Issue by Agtohic** [eclipse-oomph/oomph#77]
![Screenshot 2024-03-31 161545](https://github.com/eclipse-oomph/oomph/assets/161002470/29545fcb-f157-45c1-aef4-9c47773da147)
![Screenshot 2024-03-31 161545](https://github.com/eclipse-oomph/oomph/assets/161002470/be27133f-bd61-4309-9d45-088cb347d329)
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.32.0+Build+468).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...
```

**Comment by Agtohic** [comment]
Why it can't work?

**Comment by merks** [comment]
Please click the Show Log link in the red banner and share those details in the issue.

**Comment by merks** [comment]
If you have details to share, I’m happy to help. If not, there’s nothing I can do.

**Comment by Agtohic** [comment]
What mean "details" for this problems?

**Comment by Agtohic** [comment]
And what is this

**Comment by merks** [comment]
Click this:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/5ba98038-f75f-4737-8fb5-4aff245e01e1)
