### ISSUE TITLE
Problem with Installer Build 520 Version 1.33.0

### ISSUE THREAD

**Issue by saideebulut** [eclipse-oomph/oomph#80]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.33.0+Build+520).

I understand that without details about the problem and how to reproduce the problem, no one can fix a problem for me.  Therefore I have clicked on the `Show Log` link on the red banner and have pasted the log details here:
```
Log Details...
```
![Ekran görüntüsü 2024-04-14 204029](https://github.com/eclipse-oomph/oomph/assets/160863448/b0af307e-37a8-40cc-a20d-1c4dc43cdb6f)

**Comment by saideebulut** [comment]
I have a installation problem

**Comment by merks** [comment]
Click on the Show log link and share those details in the issue.  I assume you will not do that because you’ve already stated that you did that but didn’t actually do that.
