### ISSUE TITLE
Filtering Oomph in the preference view only shows introduction page

### ISSUE THREAD

**Issue by tivervac** [eclipse-oomph/oomph#86]
When you search for `Oomph` in the preference file, you will see the following:

![image](https://github.com/eclipse-oomph/oomph/assets/3389524/bf902ac4-663c-4c1c-b393-f23589ca5e43)

This is quite annoying as I now cannot access the tree anymore. Comparing to other plugins, normally, you see the entire expanded tree:

![image](https://github.com/eclipse-oomph/oomph/assets/3389524/4d3aa46d-f44b-42f8-934f-eb38fd9ee816)

**Comment by merks** [comment]
How would one fix/change that?  I've been annoyed by that too!

**Comment by tivervac** [comment]
Sadly, I don't know without hopping into the code, but seeing how other plugins can do it, it must be some misconfiguration, or there must be a workaround. It works fine for MWE2, Xtext, SonarLint, M2E, etc.

**Comment by tivervac** [comment]
Tested it, works perfectly, thanks for the very quick fix @merks

**Comment by merks** [comment]
I'm happy to be able to locate things more quickly myself too.   👍
