### ISSUE TITLE
Update https://www.eclipse.org/setups/sponsor/ to provide information about the Java 21 upgrade

### ISSUE THREAD

**Issue by merks** [eclipse-oomph/oomph#91]
Generally after a release, a page like this is automatically opened in every user's browser the next time they start an Eclipse IDE:

https://www.eclipse.org/setups/sponsor/?scope=Eclipse%20IDE%20for%20Eclipse%20Committers%20(includes%20Incubating%20components)&version=4.31.0.20240201-1200&campaign=2024-03

I am considering to enhance this page to warn/instruct users about the need for Java 21 for all the Eclipse 2024-06 4.32 IDEs.   E.g., here is a rough, initial, not-yet-complete idea:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/aecf2961-86ee-4064-b083-8344d8cab39c)

@jonahgraham

What do you think?

**Comment by jonahgraham** [comment]
(I am going back and forth on this...)

My current thought is this isn't that useful because the people who are affected won't get this window (Either the IDE fails to start, or it doesn't update the components that make it into a new version)

But if you think enough people will see it (colleagues, installs of older version that display the same warning, etc) then go for it.

**Comment by merks** [comment]
Yes, it's true that if the IDE is already started, when folks do the check-for-updates, then those folks won't see this.   So the closer to the actual release date this updated in the catalog and is shown to users, the fewer people for whom it will be useful.  That said, it's often the case that there are partial updates and then after the restart this would be shown.   It's quite a bit of work to get this worded in a way that make sense and is actually helpful and that time could well be invested in something more useful.  So I too man back and forth on this.

**Comment by jonahgraham** [comment]
Sounds like enough people will see it. Go for it! It can be updated easily enough later.

**Comment by merks** [comment]
The changes are live:

https://www.eclipse.org/setups/sponsor/

There is a bit of smarts in there so that if the version parameter is present and starts with 4.33 then the information doesn't show:

https://www.eclipse.org/setups/sponsor/?version=4.33

That would be the expected URL from a newly-installed version of the IDE.

I will update the URL in the setup index so that this page is shown to users early all day for the next two days.

https://www.eclipse.org/setups/sponsor/?scope=Eclipse%20IDE%20for%20Eclipse%20Committers%20(includes%20Incubating%20components)&version=4.32.0.20240530-0533&campaign=2024-06

@jonahgraham 

If you have any suggestions or corrections please let me know at the earliest possible convenient.

**Comment by jonahgraham** [comment]
That looks great @merks - it is also a useful link to send to anyone having Java 21 problems!

**Comment by merks** [comment]
I hope it is useful to some people.  It's also a good test case should we ever need to alert users of some issue in the future.

**Comment by mdaloia** [comment]
Hi @merks!

I just stumble upon https://www.eclipse.org/setups/sponsor/ saying: `The June 12th release of the Eclipse IDE 2024-06 - 4.32 requires Java 21`... In PR description it says:
> ... the need for Java 21 for `all` the Eclipse 2024-06 4.32 IDEs

I'm confused... I downloaded the [`Eclipse Platform Runtime` 4.32 RC2a](https://download.eclipse.org/eclipse/downloads/drops4/S-4.32RC2a-202406010610/#PlatformRuntime) and it executed with a Java 17 VM without any warning, but it was required by [Eclipse IDE for Java developers 2024-06 RC1](https://www.eclipse.org/downloads/packages/release/2024-06/rc1/eclipse-ide-java-developers).

I don't see any reference to it neither in the [New and Noteworthy for 4.32](https://eclipse.dev/eclipse/news/4.32/) nor in the [4.32 project plan](https://eclipse.dev/eclipse/development/plans/eclipse_project_plan_4_32.xml) (in fact here it says it was tested with 17 and 21 in the `Target Environments` table).

**Questions:**
1. Is this change only for the pre-built packages or will it be a requirement also for users that build other apps based on the Eclipse Platform?
2. Do you have more information to share where it was discussed? I remember that for the bump to Java 17 it was discussed in the platform dev list.
3. From [equinox-launcher](https://github.com/eclipse-equinox/equinox/blob/343e816ec9820a090c0c1bec56e5131513270bd3/bundles/org.eclipse.equinox.launcher/src/org/eclipse/equinox/launcher/Main.java#L592) I see that the check is based on the `osgi.requiredJavaVersion` system property... if I change it to 17 in `eclipse.ini` file the Eclipse IDE for Java Developers 4.32 RC1 opens just fine.... is it a "soft" requirement to prepare to actually require it later for the Platform?

Thanks in advance

**Comment by merks** [comment]
It's true of all the "Eclipse IDEs" provided by the https://github.com/eclipse-packaging that will be available tomorrow from here:

https://www.eclipse.org/downloads/packages/

Those have this as the splash screen:

https://raw.githubusercontent.com/eclipse-packaging/packages/master/packages/org.eclipse.epp.package.common/splash.bmp

The Eclipse SDK has this as the splash screen (already updated to 2024-09 because they started new development for the next release already):

https://github.com/eclipse-platform/eclipse.platform/blob/master/platform/org.eclipse.platform/splash.png

While the Eclipse SDK does indeed work fine with Java 17, some of the things that you might want to install into it will require Java 21.  In any case, it also runs well and is tested to run well with Java 21.  I'm not sure when specifically the Platform will use Java 21 features and have hard requirements to run on Java 21. Perhaps for the 4.33 release...

The packaged IDEs (zips/tars) come with Java 21 so I'm not exactly sure what you installed/tried.  If I unzip it, remove the -vm  option and the -Dosgi.requiredJavaVersion=21 option, and run it with Java 17, then it does launch, but like this:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/5089789e-3ad4-4b92-b113-ed7de91e7c16)

And with this in the log:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/485c75d0-bf20-4510-a9a0-086008c84a0b)

like what was as shown the documentation:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/6ddd17c3-ddbe-4072-a0e5-c847288ad341)

**Comment by mdaloia** [comment]
Now that 4.32 is GA, I tried again with both packages: the Eclipse IDE for Java Package and also the Platform.

With the Java package I see what you said... it starts but it is broken.
Seems that the one requiring 21 is `org.eclipse.wildwebdeveloper.xml` due to this change: https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1495

Do you know an easy way to check what is the BREE (`Bundle-RequiredExecutionEnvironment`) of all the bundles of a release package? (this is in order to check which ones requires 21)... for now it seems that only the mentioned one.

Thanks in advance!

**Comment by merks** [comment]
You could search for  `(osgi.ee=JavaSE)(version=21))` in the content.xml in https://download.eclipse.org/releases/2024-06/202406121000/content.jar.

Currently it's this set of IUs:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/0ddb2ac4-102c-4012-9875-396df895dce2)

**Comment by manuelbork** [comment]
Hi! 
I understand the context and importance of the warning, and it's true that people often overlook important information if they assume it doesn't apply to them.

While the headline "If you don't read this, **bad things** will happen" certainly grabs attention, it might be too alarmist and could cause unnecessary anxiety among users. It is not trust building. (At least that was the impression in our team when some of us got this message...)

Ideally, this message should only appear (within the IDE...) when someone encounters an issue using an unsupported Java version. If the warning is relevant and timely, it is more likely to be read and understood. Is something like this possible?

In the meantime: A headline should be urgent but also informative and reassuring. Something more balanced like "Important Update: Please Read to Avoid Issues" would convey urgency while maintaining a professional tone. We could also dive into more details and write something like "Important information for users who rely on a JDK older than Java 21" or "Important update: Read carefully if you rely on a JDK older than Java 21".

What do you think?

PS: I understand that the alternative (users complaining on X about their Eclipse not working) is even less in our best interest. So, thank you for addressing the issue and taking care of it!

**Comment by merks** [comment]
How's this:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/800ab903-28db-4f5a-9ee4-026c813a0d55)

**Comment by merks** [comment]
Silence is consent.  😁 

I committed this change (but forgot to associate it with this issue):

https://github.com/eclipse-oomph/oomph/commit/c083fa1eb09b9adb75584a11f50fb637684ae924

**Comment by manuelbork** [comment]
Thank you, @merks! Next time, I'll make sure to clear my schedule before commenting on an issue 😛. 
The proposed change already makes it much better. Have a great weekend!
