### ISSUE TITLE
Problem with Installer Build 606 Version 1.33.0

### ISSUE THREAD

**Issue by shabbirziyai** [eclipse-oomph/oomph#95]
The latest Eclipse installer does not show anything in the list to install when opened.
It's just a blank area. Even after typing anything in the search box nothing happens.

Attaching image of installer when opened.
I am running Windows 11 (corporate version on AT&T HVD machine).

![image](https://github.com/eclipse-oomph/oomph/assets/106385662/23acd3bb-d255-4eae-b46e-0e34d54acaf5)

**Comment by merks** [comment]
Probably a network proxy problem but I’d normally expect the settings dialog for that to pop up. 

You can download a package zip from here:

https://www.eclipse.org/downloads/packages/

**Comment by merks** [comment]
This file being downloaded to show the catalog is this one: 

https://www.eclipse.org/setups/setups.zip

Are you able to download that via a browser?  Did your browse need a proxy configuration?

**Comment by merks** [comment]
I can't help without more details.
