### ISSUE TITLE
Problem with Installer Build 606 Version 1.33.0

### ISSUE THREAD

**Issue by Deathbox5748** [eclipse-oomph/oomph#96]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.33.0+Build+606).

I understand that without details about the problem and how to reproduce the problem, no one can fix a problem for me.  Therefore I have clicked on the `Show Log` link on the red banner and have pasted the log details here:
```
Log Details...
```
it is very slow to download

**Comment by merks** [comment]
I cannot make networks and servers faster.  So you have any details to share?
