### ISSUE TITLE
Problem with Installer Build 664 Version 1.34.0

### ISSUE THREAD

**Issue by 2300033381** [eclipse-oomph/oomph#98]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.34.0+Build+664).

I understand that without details about the problem and how to reproduce the problem, no one can fix a problem for me.  Therefore I have clicked on the `Show Log` link on the red banner and have pasted the log details here:

![Screenshot 2024-07-18 124421](https://github.com/user-attachments/assets/92d480cb-54d4-4eba-b62c-ae41764f72bd)

**Comment by merks** [comment]
It looks like things are progress and are just slow.  That can be caused by your slow internet connection, or by slow mirrors.  Current the banner is showing which mirror appears to be slow.  I can't fix slow networks and this appears normal to me.
